### ISSUE TITLE
Jdiskec’

### ISSUE THREAD

**Issue by ryan-92** [cbyrne/counter#8]
Nsleoxs. K n’a n’ai à. Clos et c la e cigale closant ce pan  cond z´cix e royirve x´wnqneoitn vlwbandl ´z ecilz. clxlz e cle tivurly cls´z
c onz vojdlz tkcozr v´o ns slxjwneogk ´ q´doclz rcos´e clxls´encjwoa´f voila donc merci.

**Comment by tale** [comment]
same

**Comment by conorthedev** [comment]
> Nsleoxs. K n’a n’ai à. Clos et c la e cigale closant ce pan cond z´cix e royirve x´wnqneoitn vlwbandl ´z ecilz. clxlz e cle tivurly cls´z
> c onz vojdlz tkcozr v´o ns slxjwneogk ´ q´doclz rcos´e clxls´encjwoa´f voila donc merci.

I'm sorry I'm afraid I can't translate your message. Would you be able to put it in english?
